name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Run lint and build (always exist)
      - run: npx nx run-many -t lint --skip-nx-cache
      - run: npx nx run-many -t build --skip-nx-cache

      # Run typecheck and tests (skip if missing)
      - run: npx nx run-many -t typecheck --skip-nx-cache --ignore-missing
      - run: npx nx run-many -t test --skip-nx-cache --ignore-missing
